os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
addons:
  apt:
    sources:
      - sourceline: 'deb [trusted=yes] http://apt.zewo.io ./'
    packages:
      - zewo
install:
  - eval "$(curl -sL http://sh.zewo.io/install-zewo.sh)"
